spring:
  datasource:
      url: jdbc:mysql://${db_host}:3306/test_db
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${db_uname}
      password: ${db_pwd}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

